# Generated by Django 5.2.8 on 2025-11-18 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wa_id', models.CharField(max_length=20)),
                ('sender', models.CharField(choices=[('whatsapp', 'Whatsapp'), ('system', 'System'), ('user', 'User')], max_length=20)),
                ('receiver', models.CharField(choices=[('whatsapp', 'Whatsapp'), ('system', 'System'), ('user', 'User')], max_length=20)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
