# Generated by Django 5.2.8 on 2025-11-19 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='id_user',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='receiver',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sender',
            field=models.CharField(max_length=50),
        ),
    ]
